name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install

    - name: Deploy to EC2
      run: |
        echo "-----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASC...
        -----END PRIVATE KEY-----" > key.pem
        chmod 400 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r . ec2-user@ec2-54-234-123-45.compute-1.amazonaws.com:/home/ec2-user/your-app
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-234-123-45.compute-1.amazonaws.com "cd /home/ec2-user/your-app && npm install && pm2 restart all || pm2 start index.js"
